---
title: "Welcome To STEM MA Quantitative methods in Educational Research Blog"
author: "Richard Brock and Peter Kemp"
date: "2023-11-02"
categories: [news]
---

We will use this blog to display student work from the MA STEM Quantitative methods in Educational Research

```{r message=FALSE, include=FALSE}
#| echo: true
#| eval: true
#| message: false
# Install rworldmap package which contains country shape information
options(repos=c(CRAN="http://cran.us.r-project.org"))

install.packages("rworldmap")
install.packages("tidyverse")
install.packages("arrow")
install.packages("ggrepel")
library(rworldmap)
library(ggrepel)
library(arrow)
library(tidyverse)

PISA_2018 <- read_parquet("/Users/k1765032/Library/CloudStorage/GoogleDrive-richardandrewbrock@gmail.com/.shortcut-targets-by-id/1c3CkaEBOICzepArDfjQUP34W2BYhFjM4/PISR/Data/PISA/2018/PISA_2018_student.parquet")


  
```

```{r}
#| echo: true
#| eval: true
#| warning: false
# Create a dataframe of country latitude and longitude data
world_data <- map_data(map="world")

# Create a dataframe of mean PISA science scores, and rename CNT to region
# for the leftjoin mergining of dataframes
WorldSci<-PISA_2018%>%
  select(CNT, PV1SCIE)%>%
  group_by(CNT)%>%
  summarise(meanSci=mean(PV1SCIE, na.rm=TRUE))%>%
  rename(region=CNT)

levels(WorldSci$region)[levels(WorldSci$region)=="United Kingdom"] <- "UK"
levels(WorldSci$region)[levels(WorldSci$region)=="United States"] <- "USA"
levels(WorldSci$region)[levels(WorldSci$region)=="B-S-J-Z (China)"] <- "China"
levels(WorldSci$region)[levels(WorldSci$region)=="Russian Federation"] <- "Russia"


Viet<-PISA_2018%>%
  select(PV1SCIE, CNT)%>%
  filter(CNT=="Vietnam")
  
# Add the country latitude and longitude data to the PISA scores
WorldSci<-left_join(world_data, WorldSci, by="region")
# Use geom_map to plot the basic world map (fill is white, line colour is black)
# Use geom_polygon to plot the PISA data
# Add a colour scale

Labels<-WorldSci%>%
  group_by(region)%>%
  summarise(meanSci=mean(meanSci), lat=mean(lat), long=mean(long))%>%
  na.omit()



ggplot(data = WorldSci, aes(x=long, y=lat, group=group)) +
  geom_map(data=world_data, map=world_data, aes(map_id=region), fill="white", colour="black")+
  geom_polygon(aes(fill=meanSci)) +
  scale_fill_viridis_c(option = "viridis")+
  geom_text_repel(data=Labels, inherit.aes = F, aes(x=long, y=lat,label=region),
                  size=3)+
  ggtitle("Mean PISA scoures by country")+
  theme(plot.title = element_text(hjust = 0.5))

```
